In [ ]:
1.
Credit Card Fraud Detection
1.
Objective: You need to find anomalies in the system for the companies that have a lot of transactions with the use of cards, 
The project aims to build a credit card fraud detection model, which tells us if the transaction made by the card is fraud 
or not. So basically, we will use the transaction and their labels as fraud or non-fraud to detect if the new transaction 
made by the customer is fraud or not.
2.
Dataset: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

In [50]:
import numpy as np
import pandas as pd

# Loading Data

In [51]:
df = pd.read_csv('creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

# Data Preprocessing 

In [3]:
# check info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [4]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [5]:
df.value_counts()

Time      V1          V2          V3         V4         V5         V6         V7          V8          V9         V10        V11        V12        V13        V14        V15        V16        V17        V18        V19        V20        V21         V22        V23        V24        V25        V26        V27        V28        Amount  Class
163152.0  -1.196037    1.585949    2.883976   3.378471   1.511706   3.717077   0.585362   -0.156001    0.122648   4.217934   1.385525  -0.709405  -0.256168  -1.564352   1.693218  -0.785210  -0.228008  -0.412833   0.234834   1.375790  -0.370294    0.524395  -0.355170  -0.869790  -0.133198   0.327804  -0.035702  -0.858197  7.56    0        18
          -1.203617    1.574009    2.889277   3.381404   1.538663   3.698747   0.560211   -0.150911    0.124136   4.220998   1.384569  -0.706897  -0.256274  -1.562583   1.692915  -0.787338  -0.226776  -0.412354   0.234322   1.385597  -0.366727    0.522223  -0.357329  -0.870174  -0.134166   0.327019  -0.042648  -0.85526

In [7]:
# Check null values

df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [52]:
# Check Duplicated Values

print(df.duplicated().sum())

# Remove duplicated Values

df.drop_duplicates(inplace=True)

print(df.duplicated().sum())

1081
0


# Splitting Data

In [53]:
# Splitting the data into testing and training

x = df.drop('Class', axis=1)
y = df['Class']

print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split

x_train, x_test,y_train, y_test = train_test_split(x, y , test_size = 0.20)

(283726, 30)
(283726,)


In [54]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(226980, 30)
(226980,)
(56746, 30)
(56746,)


In [55]:
x_train

Time        V1        V2        V3        V4        V5        V6  \
27069    34372.0 -1.669464  1.817258  1.119813 -0.420054 -0.104706 -0.286452   
113358   73035.0  1.289389  0.072890 -1.121304 -0.066012  2.151471  3.366795   
254255  156645.0  1.717878 -0.765222  0.620698  1.870991 -1.183038  0.571541   
200075  133273.0  1.958426 -0.719849 -1.704841 -0.612355  1.712376  3.913679   
147799   89009.0 -1.308923  1.026465 -0.470818 -3.987627  0.169161 -1.194496   
...          ...       ...       ...       ...       ...       ...       ...   
236625  148887.0 -0.106930  1.244002 -0.010788  0.955654  0.865710 -0.821168   
81589    59004.0  1.462392 -0.487816 -0.328091 -0.965194 -0.462540 -0.605018   
244594  152411.0  1.953883 -0.530107 -0.434740 -0.003181 -0.634487 -0.244258   
203920  135031.0  2.015431 -0.226208 -0.202388  0.320838 -0.644900 -0.723152   
46299    42721.0  0.995866 -1.019487  1.555702  0.775891 -1.354370  1.510230   

              V7        V8        V9  ...       V20       V21       V22  \
27069   0.540446  0.216622  0.185078  ...  0.732818 -0.286029 -0.385382   
113358 -0.471327  0.811322 -0.079783  ... -0.015256 -0.107335 -0.431144   
254255 -1.014431  0.243811  2.038838  ... -0.100003 -0.026485  0.376577   
200075 -1.250667  1.054519  1.314240  ... -0.140324  0.192702  0.690983   
147799  0.533661  0.685142  0.554490  ... -0.463930 -0.000787 -0.316662   
...          ...       ...       ...  ...       ...       ...       ...   
236625  1.354914 -0.234610 -0.515197  ... -0.013061  0.095845  0.578328   
81589  -0.378452 -0.022942 -0.969185  ... -0.059084 -0.202263 -0.838599   
244594 -0.664132  0.147123  1.242879  ... -0.243689 -0.164217 -0.418518   
203920 -0.421189 -0.173158  0.867673  ... -0.108626 -0.204567 -0.382373   
46299  -1.469133  0.629142 -0.008448  ... -0.512195 -0.231457  0.058490   

             V23       V24       V25       V26       V27       V28  Amount  
27069   0.084001  0.203353 -0.037933  0.092424  0.804459  0.445300    8.99  
113358 -0.054979  0.985314  0.702366 -0.423353  0.024989  0.018790    3.74  
254255  0.140132  0.014921 -0.171592 -0.648864  0.112933 -0.008149   76.22  
200075  0.157264  0.726699 -0.060672 -0.192507  0.060628 -0.042583   11.50  
147799 -0.106112  0.672278  0.279120 -1.351128 -0.275235 -0.014347    7.07  
...          ...       ...       ...       ...       ...       ...     ...  
236625 -0.300715 -0.090726  0.002142 -0.367495  0.435829  0.240035    4.60  
81589   0.014368 -0.582779  0.414506 -0.441190 -0.038168 -0.012649    4.99  
244594  0.346971 -0.448829 -0.540615 -0.275520  0.000106 -0.050720   15.41  
203920  0.408794  0.056418 -0.582774  0.268234 -0.023462 -0.040806    1.00  
46299   0.017862 -0.308259  0.170611 -0.230089  0.137696  0.036171   62.00  

[226980 rows x 30 columns]

In [11]:
y_train

40147     0
225577    0
15623     0
41000     0
33402     0
         ..
206997    0
171062    0
112008    0
128592    0
235149    0
Name: Class, Length: 226980, dtype: int64

# Apply Standard Scaler

In [56]:
# Apply Standard Scaler on the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# scaler.fit(x_train)

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


print(x_train.shape)
print()
print(x_test.shape)
print()
print(x_train)
print()
print(x_test)
print()

(226980, 30)

(56746, 30)

[[-1.27251868 -0.86329961  1.10736907 ...  2.02295654  1.36812353
  -0.31819001]
 [-0.45870758  0.66018241  0.04698238 ...  0.05913948  0.05468523
  -0.33915209]
 [ 1.30118549  0.88080697 -0.46249927 ...  0.28070887 -0.02827619
  -0.04975549]
 ...
 [ 1.21206472  1.00232348 -0.31957431 ... -0.00355031 -0.15937391
  -0.29255637]
 [ 0.84623597  1.03401424 -0.13483652 ... -0.06292805 -0.12884122
  -0.35009231]
 [-1.09678196  0.50905089 -0.61706452 ...  0.34309685  0.10820857
  -0.1065328 ]]

[[-1.11985148e+00  5.85444774e-01 -1.12728036e-01 ... -1.22339172e-01
   2.97042001e-02 -2.30668295e-01]
 [ 4.89921298e-01  1.07209667e+00  3.94523938e-01 ... -2.09134826e-01
  -8.84285194e-02 -3.51050575e-01]
 [-1.26841416e+00 -8.86984151e-01 -1.34078892e+00 ... -5.88154315e-02
   3.10686982e-01  1.88932826e-01]
 ...
 [-2.02690608e-01  5.42275327e-01 -3.13181887e-02 ... -6.18192024e-04
   2.90572028e-02 -1.68021596e-01]
 [ 4.74492502e-01 -5.12742151e-01  6.67914041e-01 ... -

In [13]:
x_train

array([[-1.15255226,  0.59161917, -0.02779312, ..., -0.02226927,
         0.09695074, -0.20876965],
       [ 1.04357386, -0.3381537 ,  0.20263271, ..., -0.11009484,
        -0.30616881,  0.28121057],
       [-1.42832219,  0.56315396, -0.29724958, ...,  0.19668379,
         0.10415599, -0.14083868],
       ...,
       [-0.47049435, -0.75605012,  1.59278654, ..., -1.01735991,
         0.18863387, -0.34814864],
       [-0.33780523,  0.58141165,  0.3772475 , ...,  0.03333479,
         0.08113926, -0.34806961],
       [ 1.12719224,  0.2735658 , -2.22448471, ..., -0.44222788,
         0.17649436,  3.00793325]])

# Apply SMOTE to Handle Class Imbalance

In [57]:
# Check Class Imbalance

y_train.value_counts()

Class
0    226597
1       383
Name: count, dtype: int64

In [58]:
# Apply SMOTE Analysis

from imblearn.over_sampling import SMOTE

smote = SMOTE()

x_train,y_train = smote.fit_resample(x_train,y_train)

print(x_train.shape)
print()
print(y_train.shape)
print()

(453194, 30)

(453194,)



In [59]:
y_train.value_counts()

Class
0    226597
1    226597
Name: count, dtype: int64

# Apply PCA for Dimentionality Reduction

In [21]:
# Apply PCA for Dimentionality Reduction

from sklearn.decomposition import PCA

pca = PCA(n_components=0.99)

pca.fit(x_train)

x_train = pca.transform(x_train)
x_test = pca.transform(x_test)

print(x_train.shape)
print(x_test.shape)

(453178, 25)
(56746, 25)


# Logistic Regression

In [60]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression()

model_lr.fit(x_train,y_train)

LogisticRegression()

In [61]:
# model training score

model_lr.score(x_train,y_train)

0.9487835231710923

In [62]:
# model training score

model_lr.score(x_test,y_test)

0.9740774680153668

In [63]:
# Model Prediction

model_predicted = model_lr.predict(x_test)
model_predicted

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [64]:
# Model Accuracy Score

from sklearn.metrics import accuracy_score

accuracy_score(y_test,model_predicted)

0.9740774680153668

# Decision Tree

In [65]:
from sklearn.tree import DecisionTreeClassifier

model_dtc = DecisionTreeClassifier()

model_dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [37]:
# model training score

model_dtc.score(x_train,y_train)

1.0

In [38]:
# model testing score

model_dtc.score(x_test,y_test)

0.99749762097769

In [39]:
# mdoel prediction

model_predicted_dtc = model_dtc.predict(x_test)
model_predicted_dtc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
# Model Accuracy Score

from sklearn.metrics import accuracy_score

accuracy_score(y_test,model_predicted_dtc)

0.99749762097769

In [66]:
import time
from time import TIME

time = TIME()


# Random Forest

In [68]:
from sklearn.ensemble import RandomForestClassifier

model_rfc = RandomForestClassifier()

model_rfc.fit(x_train,y_train)

RandomForestClassifier()

In [69]:
# model training score

model_rfc.score(x_train,y_train)

1.0

In [70]:
# Model testing Score

model_rfc.score(x_test,y_test)

0.9994713283755683

In [71]:
# mdoel prediction

model_predicted_rfc = model_rfc.predict(x_test)
model_predicted_rfc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [72]:
# Model Accuracy Score

from sklearn.metrics import accuracy_score

accuracy_score(y_test,model_predicted_rfc)

0.9994713283755683

# Thank You!